services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  postgres-orders:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders -d orders"]
      interval: 5s
      timeout: 5s
      retries: 30

  postgres-payments:
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments -d payments"]
      interval: 5s
      timeout: 5s
      retries: 30

  orders:
    build:
      context: ./orders-service
    environment:
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-orders:5432/orders"
      SPRING_DATASOURCE_USERNAME: "orders"
      SPRING_DATASOURCE_PASSWORD: "orders"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASS: "guest"
      PAYMENT_REQUEST_QUEUE: "orders.payments.requested"
      PAYMENT_RESULT_QUEUE: "payments.orders.result"
      OUTBOX_PUBLISH_INTERVAL_MS: "1000"
      OUTBOX_BATCH_SIZE: "50"
      OUTBOX_LOCK_TIMEOUT_SEC: "30"
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-orders:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/dz4_frontend_service
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - orders
      - payments

  payments:
    build:
      context: ./payments-service
    environment:
      SERVER_PORT: "8081"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-payments:5432/payments"
      SPRING_DATASOURCE_USERNAME: "payments"
      SPRING_DATASOURCE_PASSWORD: "payments"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASS: "guest"
      PAYMENT_REQUEST_QUEUE: "orders.payments.requested"
      PAYMENT_RESULT_QUEUE: "payments.orders.result"
      OUTBOX_PUBLISH_INTERVAL_MS: "1000"
      OUTBOX_BATCH_SIZE: "50"
      OUTBOX_LOCK_TIMEOUT_SEC: "30"
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-payments:
        condition: service_healthy
